version: '3'

services:
  web:
    build: .
    command: >
      gunicorn -c gunicorn.py --reload "hello.app:create_app()"
    env_file:
      - 'flask.env'
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
    depends_on:
      - postgresql


  postgresql:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - 'database.env'
    volumes:
      - ./postgres:/var/lib/postgresql/data

